export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string; email: string; phone: string | null; member_number: string; role: 'member' | 'admin'; created_at: string }; Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'> & { created_at?: string }; Update: Partial<Database['public']['Tables']['profiles']['Insert']> }
      savings_accounts: { Row: { id: string; user_id: string; account_type: 'Savings' | 'Shares' | 'Special Savings'; balance: number; created_at: string }; Insert: Omit<Database['public']['Tables']['savings_accounts']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['savings_accounts']['Insert']> }
      transactions: { Row: { id: string; user_id: string; member_number: string; account_type: 'Savings' | 'Shares' | 'Special Savings'; transaction_type: 'Credit' | 'Debit'; amount: number; description: string; transaction_date: string; created_by: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['transactions']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['transactions']['Insert']> }
      loans: { Row: { id: string; user_id: string; member_number: string; principal_amount: number; interest_rate: number | null; interest_amount: number | null; total_payable: number; amount_paid: number; outstanding_balance: number; status: 'Active' | 'Completed'; start_date: string; due_date: string | null; notes: string | null; created_by: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['loans']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['loans']['Insert']> }
      loan_payments: { Row: { id: string; loan_id: string; user_id: string; member_number: string; amount: number; interest_amount: number; principal_amount: number; payment_date: string; description: string | null; created_by: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['loan_payments']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['loan_payments']['Insert']> }
    }
  }
}
